import { lightTheme } from '@/themes';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'CSS Magic',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="jp">
			<body>
				<ThemeProvider theme={lightTheme}>
					<body>
						<CssBaseline />
						<AppRouterCacheProvider>{children}</AppRouterCacheProvider>
					</body>
				</ThemeProvider>
			</body>
		</html>
	);
}
