import { CssBaseline } from '@mui/material';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'CSS Magic',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<CssBaseline />
				{children}
			</body>
		</html>
	);
}
